name: Release Docker image
on:
  release:
    types: [released]
jobs:
  release:
    name: Docker Image version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get git tag information
      uses: auguwu/git-tag-action@master
      id: tag

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.floofy.dev
        username: august
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: registry.floofy.dev/charted/devcontainer:${{steps.tag.outputs.version}}
