name: Release Docker image
on:
  release:
    types: [released]
jobs:
  release:
    name: Docker Image version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Grab version info
      id: tag
      run: |
        REF=${GITHUB_REF##refs/tags/}
        echo "::set-output name=version::$REF"

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        # https://github.com/docker/build-push-action/issues/761
        driver-opts:
          image=moby/buildkit:v0.10.6

    - name: Login into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: charted-dev
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/charted-dev/devcontainer:${{steps.tag.outputs.version}},
          ghcr.io/charted-dev/devcontainer:latest
- name: OctopusDeploy CLI
  uses: burtonr/octopus-cli-action@7.4.4
- name: Upload a Build Artifact
  uses: actions/upload-artifact@v3.1.2
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
    name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
